<?php require VIEWS_PATH.'includes/header.phtml';?>
<div class="container">
      <div class="jumbotron">
        <h2>Sobre</h2>
        
        </div>
        <div class="col-md-12">
        <h3>A instituição</h3>
        
        <p>Um texto bacana</p>
        <h3>Nossas Metas</h3>
        <p>Um texto legal</p>
        <h3>Valores</h3>
        <p>Mais um texto bacana</p>
        </div>
          
        </p>
      </div>

    </div> <!-- /container --><?php require VIEWS_PATH.'includes/footer.phtml';?>
