<?php require VIEWS_PATH.'includes/header.phtml';?>
<div class="container">
      <div class="jumbotron">
        <h2>Fale conosco</h2>
        
        </div>
        <div class="col-md-12">
        
        
        <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Nome</label>
    <input type="nome" class="form-control" id="exampleInputEmail1" aria-describedby="nome" placeholder="Nome">
    <small id="Nome" class="form-text text-muted">Nome completo.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email </label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">E-mail.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Assunto</label>
    <input type="text" class="form-control" id="assunto" aria-describedby="emailHelp" placeholder="Assunto">
    <small id="assunto" class="form-text text-muted">Assunto.</small>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Mensagem</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
</form>
  
  
        </div>
          
        </p>
      </div>

    </div> <!-- /container --><?php require VIEWS_PATH.'includes/footer.phtml';?>
