<?php require VIEWS_PATH.'includes/header.phtml';?>
<div class="container">
      <div class="jumbotron">
        <h1>Projeto 1</h1>
        <p>Projeto demonstração
        <p>
          <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
        </p>
      </div>

    </div> <!-- /container --><?php require VIEWS_PATH.'includes/footer.phtml';?>
